blank_issues_enabled: false
contact_links:
  - name: "💬 General Discussions"
    url: "https://github.com/Librefolio/LibreFolio/discussions"
    about: "For general questions, support, or showing off your setup."
